version: '3'
services:
  php:
    build: .
    container_name: bookmark
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    hostname: bookmark
    depends_on:
      - database

  database:
    image: mysql:8
    container_name: bookmark-database
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_SAVE_PATH}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"

volumes:
  mysql:
    driver: "local"
