CREATE USER IF NOT EXISTS 'default'@'%';

CREATE TABLE IF NOT EXISTS bookmark (
  id   INTEGER PRIMARY KEY AUTO_INCREMENT,
  name TEXT,
  url  TEXT
);

CREATE TABLE IF NOT EXISTS tag (
  id   INTEGER PRIMARY KEY AUTO_INCREMENT,
  bid  INTEGER,
  name TEXT
);

CREATE TABLE IF NOT EXISTS memo (
  id    INTEGER PRIMARY KEY AUTO_INCREMENT,
  bid   INTEGER,
  value TEXT
);
